### ISSUE TITLE
Possible issue with while (true)

### ISSUE THREAD

**Issue by overfl0** [Fusselwurm/arma-class-parser#18]
Shouldn't you use `while (current())` in `parseTranslationString` just the same way as you're doing it in `parseString`?

I noticed that you had a commit that was fixing the code that way and I thought that this may need the same change here: https://github.com/Fusselwurm/arma-class-parser/blob/master/src/class-parser.ts#L190

**Comment by Fusselwurm** [comment]
thank you! getting fixed with #19

**Comment by Fusselwurm** [comment]
fixed version published as 1.1.1
