### ISSUE TITLE
How is this code licensed?

### ISSUE THREAD

**Issue by overfl0** [Fusselwurm/arma-class-parser#4]
Hey!

What is the license of the code fot arma-class-parser?
You don't have any information about it on github (neither in the project settings nor in a `LICENSE` file so I need to ask here).

I'm a Python programmer and I was using your code in my python programs coupled with PyExecJS first and js2py later to allow its execution from Python. The first one is tricky to set up in Windows and the second one is quite slow because it's like emulation of Javascript code.

Because your code is quite small, I thought about porting it to Python to for greater simplicity, ability to install it with a python package manager and for greater speed, of course. That's why the license choice is important for me (since I'd probably be reusing some of your code or at least part of the constructs).

I would like to release my code on Github under the MIT license (TL;DR: you can use this code wherever you want but you need to keep the information about the author in the source) but for that to happen your code would also have to be licensed as MIT. Are you okay with this?
Otherwise, I'll probably quickly hack a simple parser in python from scratch just for my needs that I'll be ashamed of showing to the world so I'd prefer you to agree on that license, tbh ;)

I was reading your code yesterday and I plan on reporting a few issues that I've noticed there in the next few days.

**Comment by Fusselwurm** [comment]
I thought about a non-exclusive do-whatever-the-fuck-you-want licence, but MIT is fine as well ^^

**Comment by Fusselwurm** [comment]
see 145e87131a3727d898236873e29377831014c6e9 :)
