### ISSUE TITLE
parseMathExpression doesn't separate expressions well

### ISSUE THREAD

**Issue by overfl0** [Fusselwurm/arma-class-parser#5]
Is this code even needed, since it currently only handles addition and parses it wrong.

The code is:
```javascript
                return expression.split('+').map(parseNumber).reduce(function (prev, cur) {
                    return prev + cur;
                }, 0);
```

In our missions.sqm, we have:
```
position[]={12365.242,2.1711425e+020,8484.4668};
```
So `parseArray` will call `parseMathExpression` for the second value in the array.
This in turn will split it to: `2.1711425e` and `020`, parse them separately and then sum the result, which is wrong.

The value above is supposed to evaluate to `2.1711425 * 2^20 = 217114250000000000000` and parseFloat does this out of the box.
I don't know if `parseMathExpression` has ever been needed here. Maybe it was put here because the author thought this was a real mathematical addition?

**Comment by Fusselwurm** [comment]
honestly – I cant remember. Possible. XD
