### ISSUE TITLE
Unclear purpose of weHaveAStringLineBreak

### ISSUE THREAD

**Issue by overfl0** [Fusselwurm/arma-class-parser#6]
```javascript
            weHaveAStringLineBreak = function () {
                return raw.substr(currentPosition, 6).indexOf('" \\n "') === 0;
            },
```

What is the purpose of this part of the code?
It seems to check for the presence of `" \n "` (including the quotes!). I haven't seen any occurrence of such a string in our sqm files anywhere so I suspect there is some kind of mistake here.

I would have to double-check this but I think that only one `\` is needed if you mean splitting the string onto several lines. If that's the case, then the spaces around the `\n`are wrong because there could be an arbitrary number of whitespace characters on both sides of the newline character (including tabs, etc...). Also `\r\n` should be handled too probably.

**Comment by Fusselwurm** [comment]
see https://github.com/Fusselwurm/arma-class-parser/blob/master/tests.html#L18

I'm pretty sure I copied that from a real-life init clause in the mission.sqm

**Comment by Fusselwurm** [comment]
see  #1 ;)

If you can find a real-life example of the editor saving those line breaks in a different format (or with different number of spaces) we should ofc fix it. 

Actual humans will probably never try to write shit in that way – unless we're actively trying to find something to be busy about, we should probably ignore that possibility.

**Comment by overfl0** [comment]
Ugh... it looks like you are probably right.
Didn't know that the class format would be soooo wicked and I assumed this was a bug. If that's what the editor is outputting then there is no point in changing that:-|
